#!/usr/bin/env bash

set -e

_linkRCFiles() {
  case "$(uname -s)" in
  Linux)
    if ! type rcup >/dev/null 2>&1; then
      curl -LO https://thoughtbot.github.io/rcm/dist/rcm-1.3.4.tar.gz &&
        sha=$(sha256sum rcm-1.3.4.tar.gz | cut -f1 -d' ') &&
        [ "$sha" = "9b11ae37449cf4d234ec6d1348479bfed3253daba11f7e9e774059865b66c24a" ] &&
        tar -xvf rcm-1.3.4.tar.gz &&
        pushd . >/dev/null || exit

      cd rcm-1.3.4 &&
        ./configure --prefix=$HOME/.local && make && make install
      export PATH=$PATH:$HOME/.local/bin

      popd &>/dev/null || exit 1

      rm -rf rcm-1.3.4
      rm rcm-1.3.4.tar.gz
    fi
    echo Updating rc files for Linux
    RCRC=./rcrc rcup -t Linux -v
    ;;
  Darwin)
    if ! type rcup >/dev/null 2>&1; then
      brew install coreutils # for gdircolors
      brew install rcm
    fi
    echo Updating rc files for MacOS
    RCRC=./rcrc rcup -t Darwin -v
    ;;
  esac
}

_installNvm() {
  if ! declare -f nvm &>/dev/null; then
    case "$(uname -s)" in
    Linux)
      unset NVM_DIR
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
      export NVM_DIR="$HOME/.config/nvm"
      mkdir -p "$HOME/.config/nvm"
      # shellcheck disable=SC1091
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
      ;;
    Darwin)
      if [ ! -d "$HOME/.config/nvm" ]; then
        unset NVM_DIR
        mkdir -p "$HOME/.config/nvm"
        export NVM_DIR="$HOME/.config/nvm"
      fi
      if [ -z "$NVM_DIR" ]; then
        export NVM_DIR="$HOME/.config/nvm"
      fi
      brew install nvm
      # shellcheck disable=SC1091
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
      ;;
    esac
    nvm install --lts --latest-npm #install LTS version of node and npm
    nvm alias default 'lts/*'
    nvm use default
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  fi
}

_installRvmAndRuby() {
  if [ ! -s "$HOME/.rvm/scripts/rvm" ]; then
    echo "Installing rvm"
    echo "...When done, \`rvm install 3.3\` or some known ruby version and re-run setup to continue"
    if ! type gpg >/dev/null 2>&1; then
      echo
      echo "  First installing gpg"
      case "$(uname -s)" in
      Linux)
        sudo apt-get install gnupg2 -y
        ;;
      Darwin)
        brew install gnupg
        ;;
      esac
    fi
    export rvm_ignore_dotfiles=yes
    gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -sSL https://get.rvm.io | bash -s stable --ruby=3.4.4
    echo
  else
    $HOME/.rvm/scripts/rvm get head
  fi
  if ! type ruby >/dev/null 2>&1; then
    #If Error running '__rvm_make -j20', error, then `rvm cleanup all` and try again
    rvm install 3.4.4
    rvm alias create default ruby-3.4.4
  fi
}

_setupNvim() {
  echo "Setting up nvim"
  # shellcheck disable=SC1091
  . "$HOME/.config/nvim/setup"
}

_run() {
  pushd . >/dev/null || exit

  local _dotfilesDir
  _dotfilesDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
  cd "$_dotfilesDir"

  git submodule update --init --recursive

  echo
  _linkRCFiles

  echo
  ./bin/installNvm.sh

  echo
  //_installRvmAndRuby

  echo
  _setupNvim

  echo
  echo "Done"

  popd &>/dev/null || exit 1
}

_run
unset -f _run
unset -f _linkRCFiles
unset -f _installNode
unset -f _installRvmAndRuby
unset -f _setupNvim
