#### COLOUR (Solarized Light - RGB)

# default statusbar colors
set-option -g status-style fg=#b58900,bg=#eee8d5 #yellow and base2

# default window title colors
set-window-option -g window-status-style fg=#839496,bg=default #base0 and default

# active window title colors
set-window-option -g window-status-current-style fg=#cb4b16,bg=default #orange and default

# pane border
set-option -g pane-border-style fg=#eee8d5 #base2
set-option -g pane-active-border-style fg=#93a1a1 #base1

# message text
set-option -g message-style fg=#cb4b16,bg=#eee8d5 #orange and base2

# pane number display
set-option -g display-panes-active-colour "#268bd2" #blue
set-option -g display-panes-colour "#cb4b16" #orange

# clock
set-window-option -g clock-mode-colour "#859900" #green

# bell
set-window-option -g window-status-bell-style fg=#eee8d5,bg=#dc322f #base2, red

#Toggle solarized dark/light (also toggles Ghostty theme if running in Ghostty)
bind b run-shell 'tmux-toggle-solarized'
