#!/bin/sh

if type python3 >/dev/null 2>&1; then
  echo "pip install --upgrade pynvim"
  VENV_DIR="$HOME/.config/nvim/pynvim-venv"
  if [ ! -d "$VENV_DIR" ]; then
      python3 -m venv "$VENV_DIR" &> /dev/null
  fi
  "$VENV_DIR/bin/pip" install --upgrade pynvim &> /dev/null
  echo "Done: pip install --upgrade pynvim"


  # Does not work with python 3.12
  # echo "pip install --upgrade ueberzugpp"
  # #ueberzugpp is a C++ replacement of ueberzug with python bindings
  # "$VENV_DIR/bin/pip" install --upgrade ueberzugpp &> /dev/null
  # echo "Done: pip install --upgrade ueberzugpp"

  unset VENV_DIR
fi

if type cpanm >/dev/null 2>&1; then
  echo "perl: upgrade cpanm Neovim::Ext"
  cpanm -n Neovim::Ext
  echo "Done: cpanm -n Neovim::Ext"
fi

if type gem >/dev/null 2>&1; then
  echo "gem: install neovim"
  gem install neovim
  echo "Done: gem install neovim"
fi

if type npm >/dev/null 2>&1; then
  echo "npm: install neovim"
  npm install -g neovim@latest
  echo "Done: npm install neovim"

  echo "npm: install tree-sitter"
  npm install -g tree-sitter@latest
  echo "Done: npm install tree-sitter"
fi
