#!/usr/bin/env bash
echo loading ~/.bash/bash_common

# Non-Operating System Specific Aliases
# Alias ls if alias does not exist
alias ll="ls -lh"
alias lt="ls -tlAh"
alias lal="ls -lAh"
alias dir="ls -lAh"

alias k9="kill -9"
alias ssn="sudo shutdown -h now"
alias ps="ps -af"

# shell
alias ..="cd .."
alias ...="cd ../.."

mcd () { mkdir -p $1 && cd $1; }

alias mkdir="mkdir -p"
alias md="mkdir -p"

alias du="du -h"
alias df="df -h"

alias cls="clear"
alias more="less"
alias del="rm"

export PAGER="less"

#less default behaviour
export LESS="ReMqXi~g"
#R Raw color codes in output (don't remove color codes)
#e exit the second time it reaches end of line
#M verbose prompt
#q quiet operation
#X disables sending the termcap initialization/deinitialization strings
#  ie prevents clear screen
#i searches ignore case
#~ - Don't show those weird ~ symbols on lines after EOF
#g - Highlight results when searching with slash key (/)

# Less coloring
#export LESS_TERMCAP_mb=$'\E[01;31m'
#export LESS_TERMCAP_md=$'\E[01;31m'
#export LESS_TERMCAP_me=$'\E[0m'
#export LESS_TERMCAP_se=$'\E[0m'
#export LESS_TERMCAP_so=$'\E[01;44;33m'
#export LESS_TERMCAP_ue=$'\E[0m'
#export LESS_TERMCAP_us=$'\E[01;32m'

# Grep
export GREP_OPTIONS="--binary-files=without-match --color=auto --exclude=tags --exclude=TAGS --exclude-dir=.git --exclude-dir=.svn --exclude-dir=.hg"

# History
shopt -s histappend                         # Append each(!) history entry from all terminals realtime(not after sesion ending)
shopt -s cmdhist                            # store multiline commands as 1 line
shopt -s cdspell                            # spelling error correction
shopt -s checkwinsize                       # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
# HISTCONTRL settings: "ignoreboth" is same as "ignorespace:ignoredups"
# ignore commands that begin with space and ignore duplicate commmands
export HISTCONTROL="ignoreboth"
# Don't include simple commands in history
# & supresses duplicate entries
# [ \t]* supress commands beginning with whitespace (space or tab) followed by * (anything) (this is not a regex)
# ?:?? - any 1 or 2 char commands including ls, fg, bg, etc..)
# common commands like "history", "clear", "cls", "exit", "pwd", etc
export HISTIGNORE="&:[ \t]*:?:??:clear:cls:exit:pwd:history*:%[0-9]:"
export HISTFILESIZE=5000                    # history file size

#Set $XML_CATALOG_FILES for programs like xmllint.  vim's syntastic uses xmllint to validate xml files
#https://github.com/darcyparker/XMLCatalog is my XMLCatalog
if [ -z $XML_CATALOG_FILES ]; then
  [ -e "$HOME/src/XMLCatalog/catalog.xml" ] && export XML_CATALOG_FILES="$HOME/src/XMLCatalog/catalog.xml"
fi

echo done loading ~/.bash/bash_common
