#!/usr/bin/env bash

#Linux/Cygwin Colors for ls
export LS_COLORS="di=1;32;40:ln=36;40:so=34;40:pi=34;40:ex=1;35;40:bd=34;40:cd=34;40:su=1;35;40:sg=1;35;40:tw=32;40:ow=32;40:"
export DISPLAY=localhost:0

# Aliases specific to Linux
alias ls="ls --color -F"
