#!/usr/bin/env bash

# Remember to setup cygwin prompt here
# chere -i -t mintty -s bash -e "Open cygwin prompt here"

# Remove /cygdrive/d/bin_win32 from path while in cygwin
# echo $PATH
#export PATH=$(echo $PATH | sed -e 's;:\?/cygdrive/d/bin_win32;;' -e 's;cygdrive/d/bin_win32:\?;;' -e 's;:\?/cygdrive/d/opt/Git/cmd:\?;;' -e 's;:\?/cygdrive/d/opt/Python27:\?;;' )

# Remove /cygdrive/d/opt/ruby193/bin from path
#export PATH=$(echo $PATH | sed -e 's;:\?/cygdrive/d/opt/ruby193/bin;;' -e 's;:\?/cygdrive/d/opt/GnuWin32/bin;;')

#Set home for cygwin (This resolves to a different location than mingw's msys)
#Note: Not sharing home folders between msys, cygwin and win32 vim anymore because of challenges
#      with permissions and ln -s for paths like /c/* and /cygdrive/c/*
#export HOME=$(echo /home/`whoami | tr 'A-Z' 'a-z'`)
#See http://www.cygwin.com/cygwin-ug-net/using-cygwinenv.html
# Note: Not using obsolete options
export CYGWIN="nodosfilewarning"
unset PYTHONHOME

#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/strawberry\/c\/bin:\?//g" )
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/strawberry\/perl\/site\/bin:\?//g" )
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/strawberry\/perl\/bin:\?//g" )
##Interesting that the space " ", and the brackets "(" and ")" do not need to be escaped here...
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/Program Files (x86)\/Git\/cmd:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/Program Files (x86)\/GitExtensions:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/Program Files\/Mercurial:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/ruby193\/bin:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/Python27\/Scripts:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/Python27\/lib\/site-packages\/django\/bin:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/bin\/Python27:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/Program Files (x86)\/Lua\/5.1\/clibs:\?//g")
#export PATH=$(echo $PATH | sed -e "s/\/cygdrive\/c\/Program Files (x86)\/Lua\/5.1:\?//g")

#Linux/Cygwin Colors for ls
export LS_COLORS="di=1;32;40:ln=36;40:so=34;40:pi=34;40:ex=1;35;40:bd=34;40:cd=34;40:su=1;35;40:sg=1;35;40:tw=32;40:ow=32;40:"
export DISPLAY=localhost:0
export SHELL=/bin/bash

# Aliases specific to Cygwin (on Windows)

# which will look for aliases, functions and binaries
if [[ ! `declare -F which` ]]; then
  which () { (alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@; }
  export -f which
fi

alias ls="ls --color -F"

cprograms="c:\\Program Files (x86)"
ucprograms=`cygpath -u "$cprograms"`

# Get NPM Prefix and convert it for cygwin
# Note, on windows, there is no bin folder under npm's prefix
# All commands are in npm's prefix folder
NPMPREFIXBIN=`npm config get prefix`
NPMPREFIXBIN=`cygpath -u "$NPMPREFIXBIN"`

alias desktop="cd `cygpath $USERPROFILE`/Desktop"
alias downloads="cd `cygpath $USERPROFILE`/Downloads"
alias mydocs="cd `cygpath $USERPROFILE`/Documents"
alias work="cd /cygdrive/d/work"
alias dropbox="cd `cygpath $USERPROFILE`/Dropbox"

alias cs=cygstart

#javascript aliases (Rhino)
alias js="java -cp d:\\\\jars\\\\js.jar org.mozilla.javascript.tools.shell.Main -opt -1"
alias jsd="cygstart `which javaw` -cp d:\\\\jars\\\\js.jar org.mozilla.javascript.tools.debugger.Main"

alias saxon="java -jar '`cygpath -wp /cygdrive/d/jars/saxon9.jar`'"

alias nginx="/usr/local/nginx/sbin/nginx.exe"

alias gvim="cyg-wrapper.sh '$ucprograms/Vim/vim73/gvim.exe' --binary-opt=-c,--cmd,-T,-t,--servername,--remote-send,--remote-expr"

# Reduce is a computer algebra system
#alias reduce="/cygdrive/c/reduce/reduce.exe"

alias backupto="BackupTo.cmd"

alias hpcalc="cygstart cscript  \"C:\Program Files (x86)\HP-Emulators\Emu48\Emu48.vbs\" \"D:\Users\dparker\documents\Hp48gx-darcy.E48\" > /dev/null"

alias yed="cygstart /cygdrive/c/Program\ Files\ \(x86\)/yWorks/yEd/yed.exe"
alias inkscape="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Inkscape/inkscape.exe"
alias notepad++="cygstart /cygdrive/c/Program\ Files\ \(x86\)/notepad++/notepad++.exe"
alias gimp="cygstart /cygdrive/c/Program\ Files/GIMP\ 2/bin/gimp-2.6.exe"
alias filezilla="cygstart /cygdrive/c/Program\ Files\ \(x86\)/FileZilla\ FTP\ Client/filezilla.exe"
alias acrobat="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Adobe/Reader\ 10.0/Reader/AcroRd32.exe"
alias handbrake="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Handbrake/Handbrake.exe"
alias 7zip="cygstart /cygdrive/c/Program\ Files/7-Zip/7zFM.exe"
alias freemind="cygstart /cygdrive/c/Program\ Files\ \(x86\)/FreeMind/Freemind.exe"
alias windirstat="cygstart /cygdrive/c/Program\ Files\ \(x86\)/WinDirStat/windirstat.exe"
alias vnc="cygstart /cygdrive/c/Program\ Files\ \(x86\)/TightVNC/vncviewer.exe"
alias skype="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Skype/Phone/Skype.exe"
alias yammer="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Yammer/Yammer.exe"

alias ie="cygstart /cygdrive/c/Program\ Files/Internet\ Explorer/iexplore.exe"
alias chrome="cygstart /cygdrive/d/Users/dparker/AppData/Local/Google/Chrome/Application/chrome.exe"
alias firefox="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Mozilla\ Firefox/firefox.exe"

alias explore='cyg-wrapper.sh "explorer" --slashed-opt'

#Alternate (may be better...)
#alias explorer="cygstart -x ."
alias remotedesktop="cygstart `which mstsc.exe`"

alias outlook="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/outlook.exe"
alias excel="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/excel.exe"
alias word="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/winword.exe"
alias ppt="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/powerpnt.exe"
alias msaccess="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/msaccess.exe"
alias msproject="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/winproj.exe"
alias onenote="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/onenote.exe"
alias visio="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Office/Office14/visio.exe"
alias lync="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Lync/communicator.exe"
alias hipchat="cygstart /cygdrive/c/Program\ Files\ \(x86\)/HipChat/HipChat/HipChat.exe"
alias quassel="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Quassel/bin/quassel.exe"

alias mindmap="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Mindjet/MindManager\ 10/MindManager.exe"
alias vmware="cygstart /cygdrive/c/Program\ Files\ \(x86\)/VMware/VMware\ Workstation/vmware.exe"
alias beyondcompare="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Beyond\ Compare\ 2/BC2.exe"

alias wf4="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Wildfire_4.0-Workingdir /cygdrive/d/ptc/proeWildfire4.0_M220/bin/proe.exe"
alias wf5="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Wildfire_5.0-Workingdir /cygdrive/d/ptc/Creo\ Elements/Pro5.0_M140/bin/proe.exe"
alias creo1p="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Creo_1.0-Workingdir /cygdrive/d/ptc/Creo\ 1.0_m040/Parametric/bin/parametric.exe"
alias creo1d="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Creo_1.0_Direct_WorkingDir /cygdrive/d/ptc/Creo\ 1.0_m040/Direct/bin/direct.exe"
alias creo2p="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Creo_2.0-Workingdir /cygdrive/d/ptc/Creo\ 2.0/Parametric/bin/parametric.exe"
alias creo2d="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Creo_2.0_Direct_WorkingDir /cygdrive/d/ptc/Creo\ 2.0/Direct/bin/direct.exe"
alias creop="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Creo_2.0-Workingdir /cygdrive/d/ptc/Creo\ 2.0/Parametric/bin/parametric.exe"
alias creod="cygstart -d /cygdrive/d/ptc/pro_workingdirs/Creo_2.0_Direct_WorkingDir /cygdrive/d/ptc/Creo\ 2.0/Direct/bin/direct.exe"
alias mathcad15="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Mathcad/Mathcad\ 15/mathcad.exe"
alias mathcadprime="cygstart /cygdrive/c/Program\ Files\ \(x86\)/Mathcad/Mathcad\ Prime\ 1.0/mathcadprime.exe"
alias arbortext="cygstart /cygdrive/c/Program\ Files\ \(x86\)/PTC/Arbortext\ Editor/bin/editor.exe"

unset cprograms
unset ucprograms
