#!/usr/bin/env bash
# don't set prompt if this is not interactive shell
[[ $- != *i* ]]  &&  return

# Colorized prompt, with different username colors for different systems.
#

# Color codes
txtblk='\[\e[0;30m\]' # Black - Regular
txtred='\[\e[0;31m\]' # Red
txtgrn='\[\e[0;32m\]' # Green
txtylw='\[\e[0;33m\]' # Yellow
txtblu='\[\e[0;34m\]' # Blue
txtpur='\[\e[0;35m\]' # Purple
txtcyn='\[\e[0;36m\]' # Cyan
txtwht='\[\e[0;37m\]' # White
bldblk='\[\e[1;30m\]' # Black - Bold
bldred='\[\e[1;31m\]' # Red
bldgrn='\[\e[1;32m\]' # Green
bldylw='\[\e[1;33m\]' # Yellow
bldblu='\[\e[1;34m\]' # Blue
bldpur='\[\e[1;35m\]' # Purple
bldcyn='\[\e[1;36m\]' # Cyan
bldwht='\[\e[1;37m\]' # White
unkblk='\[\e[4;30m\]' # Black - Underline
undred='\[\e[4;31m\]' # Red
undgrn='\[\e[4;32m\]' # Green
undylw='\[\e[4;33m\]' # Yellow
undblu='\[\e[4;34m\]' # Blue
undpur='\[\e[4;35m\]' # Purple
undcyn='\[\e[4;36m\]' # Cyan
undwht='\[\e[4;37m\]' # White
bakblk='\[\e[40m\]'   # Black - Background
bakred='\[\e[41m\]'   # Red
badgrn='\[\e[42m\]'   # Green
bakylw='\[\e[43m\]'   # Yellow
bakblu='\[\e[44m\]'   # Blue
bakpur='\[\e[45m\]'   # Purple
bakcyn='\[\e[46m\]'   # Cyan
bakwht='\[\e[47m\]'   # White
end='\[\e[0m\]'    # Text Reset

#See http://ithaca.arpinum.org/2013/01/02/git-prompt.html
get_dir() {
  printf "%s" $(pwd | sed "s:$HOME:~:")
}

get_sha() {
  git rev-parse --short HEAD 2>/dev/null
}

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_DESCRIBE_STYLE="branch"
GIT_PS1_SHOWUPSTREAM="auto git verbose"

#Source git-prompt functions
. ~/.bash/git-prompt.sh

export PS1="${txtgrn}\#${end} ${undcyn}\u@\h${end}:\w${bldylw}\$(__git_ps1)${end} \\\$"

unset txtblk
unset txtred
unset txtgrn
unset txtylw
unset txtblu
unset txtpur
unset txtcyn
unset txtwht
unset bldblk
unset bldred
unset bldgrn
unset bldylw
unset bldblu
unset bldpur
unset bldcyn
unset bldwht
unset unkblk
unset undred
unset undgrn
unset undylw
unset undblu
unset undpur
unset undcyn
unset undwht
unset bakblk
unset bakred
unset badgrn
unset bakylw
unset bakblu
unset bakpur
unset bakcyn
unset bakwht
unset end
