#!/usr/bin/env bash
echo loading ~/.bash/bash_darwin
# Aliases specific to OS X

# which will look for aliases, functions and binaries
if [[ ! `declare -F which` ]]; then
  which () { (alias; declare -f) | gwhich --tty-only --read-alias --read-functions --show-tilde --show-dot $@; }
  export -f which
fi

brewprefix=`brew --prefix`
if [ -f ${brewprefix}/etc/bash_completion ]; then
  . ${brewprefix}/etc/bash_completion
fi
unset brewprefix

if [ -s "/usr/libexec/java_home" ]; then
  export JAVA_HOME=`/usr/libexec/java_home`
else
  export JAVA_HOME=/Library/Java/Home
fi

alias ls="ls -F"

#MS Office Aliases
alias word="open -a Microsoft\ Word"
alias excel="open -a Microsoft\ Excel"
alias ppt="open -a Microsoft\ Powerpoint"

alias xcode="open -a Xcode.app"
alias itunes="open -a iTunes.app"
alias facetime="open -a facetime.app"

alias address="open -a Address\ Book"
alias activity="open -a Activity\ Monitor"
alias textedit="open -a TextEdit.app"

alias filezilla="open -a Filezilla"
alias chrome="open -a Google\ Chrome"
alias firefox="open -a Firefox"
alias mu="open -a muCommander"
alias yed="open -a yEd"

alias desktop="cd ~/Desktop"

#copy the working directory into the clipboard
alias cwd="pwd | pbcopy"

# Terminal shortcuts
alias .t="~/bin/terminal --new-tab"
alias .w="~/bin/terminal --new-window"

alias gvim="mvim"

export EDITOR="vim"
export GIT_EDITOR="vim -f"

#Set colors for OS X (BSD)
export CLICOLOR=1
export LSCOLORS="CxgxexexFxexexFxFxcxcx"
# Colors
#   a     black
#   b     red
#   c     green
#   d     brown
#   e     blue
#   f     magenta
#   g     cyan
#   h     light grey
#   A     bold black, usually shows up as dark grey
#   B     bold red
#   C     bold green
#   D     bold brown, usually shows up as yellow
#   E     bold blue
#   F     bold magenta
#   G     bold cyan
#   H     bold light grey; looks like bright white
#   x     default foreground or background
# Order of colors in LSCOLORS, specified in pairs (foreground/background) (22 chars)
#   1. directory
#   2. symbolic link
#   3. socket
#   4. pipe
#   5. executable
#   6. block special
#   7. character special
#   8. executable with setuid bit set
#   9. executable with setgid bit set
#   10. directory writable to others, with sticky bit
#   11. directory writable to others, without sticky bit#
