#!/bin/bash
so() { [ -s $1 ] && source $1; }

# Identify env with uname, make it lower case, only take first part before _
# ENV_NAME is used to call appropriate bash options for the environment. (ie darwin, cygwin, etc...)
export ENV_NAME=$(uname -s | tr 'A-Z' 'a-z' | sed -e 's/_.*//')
#export ENV_NAME=$(uname -s | tr 'A-Z' 'a-z' | awk 'BEGIN {FS="_"};{print $1}')

#Load Env specific bash stuff first
#  This is particularly important for cygwin because settings like
#  `export CYGWIN="..."` needs to be set before some stuff like nodejs commands
#  will give an error message

so ~/.bash/bash_${ENV_NAME} # Env specific bash stuff
so ~/.bash/bash_common # Common bash stuff
so ~/.bash/bash_prompt

# Call useful bash snippets
#so ~/.bash/pathed_cd
# so ~/.bash/saveMYIP

# Move (or Add) /usr/local/bin to the front of the path
[ -d /usr/local/bin ] && export PATH=$(echo /usr/local/bin:$PATH | sed -e 's;:/usr/local/bin;;')

# Move (or Add) npm's bin folder to the front of the path
NPMPREFIX=`npm config get prefix`
[ -d $NPMPREFIX/bin ] && export PATH=$(echo $NPMPREFIX/bin:$PATH | sed -e 's;:$NPMPREFIX/bin;;')
unset NPMPREFIX

# if there is a bin folder in home, add it to PATH
[ -d ~/bin ] && export PATH=~/bin:$PATH
